# Generated by Django 5.2.7 on 2025-10-17 08:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('notes', models.TextField(blank=True, help_text='Preferencias u observaciones del huésped', verbose_name='notas')),
            ],
            options={
                'verbose_name': 'Huésped',
                'verbose_name_plural': 'Huéspedes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='check-in')),
                ('check_out', models.DateField(verbose_name='check-out')),
                ('companions', models.PositiveSmallIntegerField(blank=True, help_text='Número de acompañantes (sin contar al huésped principal)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='acompañantes')),
                ('source', models.CharField(choices=[('booking', 'Booking'), ('airbnb', 'Airbnb'), ('direct', 'Directo'), ('other', 'Otro')], default='direct', max_length=20, verbose_name='fuente')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Valoración del huésped de 1 a 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='valoración')),
                ('comments', models.TextField(blank=True, verbose_name='comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='base.guest', verbose_name='huésped')),
            ],
            options={
                'verbose_name': 'Estancia',
                'verbose_name_plural': 'Estancias',
                'ordering': ['-check_in', 'guest__last_name'],
                'indexes': [models.Index(fields=['guest', 'check_in'], name='stay_guest_checkin_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='stay_checkout_after_checkin')],
            },
        ),
    ]
